### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by mansam**
Signed-off-by: Sam Lucidi <slucidi@redhat.com>

### CODE REVIEW

**Review by pkliczewski — APPROVED** [review]

**Comment by pkliczewski** [comment]
@nunnatsa FYI

**Review by ghost — APPROVED** [review]
LGTM

**Comment by pkliczewski** [comment]
@mansam please take a look at failing test:

> Operator resource test 
>  Test CRD schemas
>  /home/travis/gopath/src/github.com/kubevirt/vm-import-operator/pkg/operator/resources/operator/operator_test.go:42
>[It] Test CRD schemas
>  /home/travis/gopath/src/github.com/kubevirt/vm-import-operator/pkg/operator/resources/operator/operator_test.go:42
>• Failure [0.040 seconds]

**Comment by mansam** [comment]
@pkliczewski That's the erroneous test failure I mentioned in https://github.com/kubevirt/vm-import-operator/pull/446. It's due to operator-utils' GetMissingEntries not handling pointers to metav1.Time. The times in the VirtualMachineImportStatus also generate the same errors, but the test ignores the status subresource so it's not noticed.

**Comment by mansam** [comment]
Investigating the Prow failure. Retesting to see if happens consistently.

/retest

**Review by jakub-dzon — APPROVED** [review]

**Comment by pkliczewski** [comment]
> @pkliczewski That's the erroneous test failure I mentioned in #446. It's due to operator-utils' GetMissingEntries not handling pointers to metav1.Time. The times in the VirtualMachineImportStatus also generate the same errors, but the test ignores the status subresource so it's not noticed.

@jakub-dzon Would mind taking a look ^^

**Comment by pkliczewski** [comment]
@mansam Please push the new version of images

**Pull request merged**
