### PR TITLE
Using controller-lifecycle-operator-sdk

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR makes use of new, common controller-lifecycle-operator-sdk that unifies HCO-deployable operator code.
The SDK: https://github.com/kubevirt/controller-lifecycle-operator-sdk

Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

**Review by machacekondra — APPROVED** [review]

**Comment by pkliczewski** [comment]
@jakub-dzon Do you consider it to be ready? When do you expect to have CDI PR merged?

**Comment by jakub-dzon** [comment]
For the current state of master branch, it's ready. It will need work after https://github.com/kubevirt/vm-import-operator/pull/390 is merged.
As for CDI - I'm finishing working on https://github.com/kubevirt/containerized-data-importer/pull/1350#issuecomment-685855373

**Review by pkliczewski — APPROVED** [review]

**Pull request merged**
