### PR TITLE
Release v0.1.0

### PR DESCRIPTION
**Pull request by jakub-dzon**
Releasing v0.0.4 as v0.1.0 into release-0.1 line branch.
```release-note
NONE
```

Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

**Review by pkliczewski — APPROVED** [review]

**Comment by pkliczewski** [comment]
@jakub-dzon I am not sure why we should have kubevirt version bump as part of the stable branch.

**Comment by masayag** [comment]
> @jakub-dzon I am not sure why we should have kubevirt version bump as part of the stable branch.

I'd also prefer to keep the patch only about bumping the version and not include other changes as part of it.

**Comment by jakub-dzon** [comment]
Without that change the functional tests will fail, as we always take the newest release, and v0.30.4 proved to introduce changes that break our functionality. I wanted to avoid having a release PR with failed functional tests.

**Review by masayag — APPROVED** [review]

**Comment by masayag** [comment]
> Without that change the functional tests will fail, as we always take the newest release, and v0.30.4 proved to introduce changes that break our functionality. I wanted to avoid having a release PR with failed functional tests.

Thanks for the explanation. In that case we'll have to revert the changes related to CDI and kubevirtci versions. Should an issue track this ? Also, are there known issues that can be reported as bugs to CDI/kubevirt ?

**Comment by jakub-dzon** [comment]
@masayag: Ondra has already implemented proper fix on the master branch: https://github.com/kubevirt/vm-import-operator/pull/338; the PR also explains what was the issue. I didn't want to pull that in, as it changes the production code. IMO we should backport it and ship in v0.1.1.

**Comment by pkliczewski** [comment]
@machacekondra what do you think?

**Comment by machacekondra** [comment]
I agree with Jakub. Let's release the fix with another version and let's bump the kubevirt & CDI versions here.

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
