### PR TITLE
Restore v1alpha1 types

### PR DESCRIPTION
**Pull request by pkliczewski**
We need to keep our older types because they are needed by HCO. 

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Review by jakub-dzon — APPROVED** [review]

**Comment by pkliczewski** [comment]
Functional test failure not related to this PR. I opened an issue https://github.com/kubevirt/vm-import-operator/issues/374 to track the failure.

**Comment by pkliczewski** [comment]
issue update with new storage related failure

**Pull request merged**
