### PR TITLE
VM Storage validation functional tests

### PR DESCRIPTION
**Pull request by jakub-dzon**
```release-note
NONE
```
Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
Looks good to me, let's wait on CI

**Review by masayag — APPROVED** [review]

**Comment by masayag** [comment]
@jakub-dzon @machacekondra tests looks good, however, will it make sense to move ovirt specific tests and resources (templates, responses) into provider's specific folder so they co-exist with future providers.

**Comment by jakub-dzon** [comment]
> @jakub-dzon @machacekondra tests looks good, however, will it make sense to move ovirt specific tests and resources (templates, responses) into provider's specific folder so they co-exist with future providers.

Good idea! I will move them.

**Comment by jakub-dzon** [comment]
@masayag - maybe in another PR? It would add a lot of noise to this one.

**Comment by masayag** [comment]
> @masayag - maybe in another PR? It would add a lot of noise to this one.

Definitely in a different PR :-) this one is acked by me already and once travis is happy - it can be merged.

**Comment by jakub-dzon** [comment]
I think Ondra has been investigating the stability issues in the controller.
@machacekondra - any luck finding the solution for the DV watch problems?

**Review by pkliczewski — APPROVED** [review]

**Comment by machacekondra** [comment]
No luck so far, I've enabled the fluentd for the tests so it's easier to debug the crash import pod and  searching for issues there right now.

**Pull request merged**
