### PR TITLE
Reduce restrictions on targer in mappings

### PR DESCRIPTION
**Pull request by pkliczewski**
We allow for target not to be there and we would use defaults.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by pkliczewski** [comment]
@suomiy FYI

**Review by jakub-dzon — APPROVED** [review]

**Review by machacekondra — APPROVED** [review]

**Comment by masayag** [comment]
@jakub-dzon could you update design doc about this change ? for each type disk-mapping/storage-mapping/network-mapping what is assumed to be the defaults to be set by the controller.

**Comment by jakub-dzon** [comment]
Sure, I will.

**Pull request merged**
