### PR TITLE
Functional tests for VM validation

### PR DESCRIPTION
**Pull request by jakub-dzon**
```release-note
NONE
```
Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

**Review by pkliczewski — APPROVED** [review]

**Comment by machacekondra** [comment]
The random test failure seems to be an issue with this method: https://github.com/kubevirt/vm-import-operator/blob/master/pkg/controller/virtualmachineimport/virtualmachineimport_controller.go#L539 I am investigating.

**Comment by jakub-dzon** [comment]
@machacekondra Is it possible that the problem is with the performance of the environment and timeouts while waiting for expected conditions are too short?

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
