### PR TITLE
Use VM UUID and disk key to name DataVolumes for vSphere VMs

### PR DESCRIPTION
**Pull request by mansam**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1898840

Signed-off-by: Sam Lucidi <slucidi@redhat.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by pkliczewski — APPROVED** [review]
Looks good to me, please make CI green

**Comment by mansam** [comment]
Something's wrong here, It looks like Prow actually failed, but github sees it as success? Please do not merge until this is resolved.

**Comment by mansam** [comment]
These tests seem to be passing locally. Retesting.

/retest

**Comment by mansam** [comment]
Prow failed in 11 seconds again though still showing green, with the following message:

```
 + /home/prow/go/src/github.com/kubevirt/vm-import-operator/_kubevirtci/cluster-up/up.sh
Download the image docker.io/kubevirtci/k8s-1.18@sha256:906af927cd0a998166d12c61162db2a0eb395c9e65d537ce7d1af2d603cb8690
Downloading ...................................................................................................
{"component":"entrypoint","file":"prow/entrypoint/run.go:168","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2020-12-10T17:29:16Z"} 
```
I have no idea what the cause of that would be. @pkliczewski have you seen a CI failure like this before?

**Comment by pkliczewski** [comment]
> I have no idea what the cause of that would be. @pkliczewski have you seen a CI failure like this before?

No. Looks very strange

**Pull request merged**
