### PR TITLE
Extend VMware tests

### PR DESCRIPTION
**Pull request by mansam**
Adds additional e2e tests for VMware, and includes fixes for some issues revealed by the tests.

* Fixed example documentation
* Fixed datastore mapping by name
* Fixed mapping of VirtualEthernetCards connected to DistributedVirtualSwitches.

Signed-off-by: Sam Lucidi <slucidi@redhat.com>

### CODE REVIEW

**Review by jakub-dzon — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by mansam** [comment]
I'm not sure what these oVirt test failures are, hoping it's a transient thing.

/retest

**Comment by pkliczewski** [comment]
Let's wait on CI to be green

**Comment by pkliczewski** [comment]
It seems like the build failed due to CDI issues.
/retest

**Pull request merged**
