### PR TITLE
Config-map based controller configuration

### PR DESCRIPTION
**Pull request by jakub-dzon**
This PR adds controller configuration provider that is backed by a dedicated ConfigMap. The configuration provided by it is not used yet. 

In preparation for #356 implementation.

```release-notes
NONE
```
Signed-off-by: Jakub Dzon <jdzon@redhat.com>

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
Are there any changes to [documentation](https://github.com/kubevirt/vm-import-operator/blob/master/docs/design.md)? If so please update

**Comment by jakub-dzon** [comment]
@pkliczewski - not in this PR - from user perspective the ConfigMap-based configuration can't be used yet.

**Review by pkliczewski — APPROVED** [review]

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
