### PR TITLE
client: connect oVirt client only when needed

### LINKED ISSUE #64: Don't reconnect to target infra if not needed
It may be very time consuming to connect to target infra, so don't connect there if not needed.

### PR DESCRIPTION
**Pull request by pkliczewski**
In this PR we only use oVirt client when needed. It is connected on demand
whenever there is a need to fetch some data or perform any actions in
source infrastructure.

Fixes: https://github.com/kubevirt/vm-import-operator/issues/64 

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Review by masayag — APPROVED** [review]
Looks good to me

**Review by jakub-dzon — APPROVED** [review]
It looks good.

Is there still a need for a generic client factory and interface? oVirt client is created and used only by the oVirt provider Plus the controller doesn't need to know about the factory either.

**Comment by pkliczewski** [comment]
@jakub-dzon Yes, we use client factory. In the future we can extend it to make other clients. The interface defines how those clients should look like.

**Comment by jakub-dzon** [comment]
I don't see any place it is used outside of the concrete, oVirt-specific provider - both `VMClient` and `Factory` (besides passing it to the provider "constructor")

Other clients may require different API, tailored to the specific provider. In controller tests provider can be mocked, not the client factory.

**Comment by pkliczewski** [comment]
`Factory` with the client interface is stored in `ReconcileVirtualMachineImport` when we create new reconciler. The idea was that it can be used for other providers in the future. Clients for other providers  can have their own interface(s) but we need our `VMClient` to implement mocks.

**Comment by pkliczewski** [comment]
As outcome of the conversation following issue was created https://github.com/kubevirt/vm-import-operator/issues/125

**Review by machacekondra — APPROVED** [review]

**Pull request merged**
