### PR TITLE
travis: update operator-sdk version

### PR DESCRIPTION
**Pull request by pkliczewski**
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

### CODE REVIEW

**Comment by masayag** [comment]
@pkliczewski is it aligned with the version used by HCO and other kubevirt operators ?  Does it have to be ?

**Comment by pkliczewski** [comment]
> @pkliczewski is it aligned with the version used by HCO and other kubevirt operators ? Does it have to be ?

Good question. It aligns with the versions we you and I are using. I will check.

**Comment by pkliczewski** [comment]
Checking other projects depts let's close it for now.

**Pull request closed without merging**
